FROM golang:1.21 as builder
WORKDIR /usr/src/ytstalker
COPY go.mod go.sum .
RUN go mod download
COPY cmd cmd/
RUN CGO_ENABLED=0 go build -v -o /usr/bin/ytstalker/tele ./cmd/tele

FROM gcr.io/distroless/static-debian11
WORKDIR /usr/bin/ytstalker
COPY --from=builder /usr/bin/ytstalker/tele .
ENTRYPOINT ["/usr/bin/ytstalker/tele"]