version: '3.8'

networks:
  app:
    driver: bridge

services:
  app:
    image: ghcr.io/thedmdim/ytstalker
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.ytstalker.rule=Host(`dmkit.ru`)
      - traefik.http.routers.ytstalker.entrypoints=websecure
      - traefik.http.routers.ytstalker.tls.certresolver=letsencrypt
    volumes:
      - ./db:/usr/bin/ytstalker/db
    environment:
      DSN: db/${DSN:-server.db}
      YT_API_KEYS: ${YT_API_KEYS}
      YT_API_MAX_TRIES: ${YT_API_MAX_TRIES}

    networks:
      - app

  traefik:
    image: docker.io/traefik
    restart: always
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --global.sendAnonymousUsage=false

      # entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # redirect http to https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      
      # let's encrypt resolver
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    labels: 
      traefik.enable: "true"
    volumes:
      - ./letsencrypt:/letsencrypt:rw
      - /run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app
