version: '3.9'

networks:
  app:
    driver: bridge

services:
    app:
        build: .
        labels:
          - traefik.enable=true
          - traefik.http.routers.app.rule=Host(`ytstalker.fun`)
          - traefik.http.routers.app.entrypoints=websecure
          - traefik.http.routers.app.tls.certresolver=letsencrypt
        volumes:
          - .:/app
        networks:
          - app

    traefik:
        image: docker.io/traefik
        restart: always
        command:
            - --log.level=DEBUG
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --global.sendAnonymousUsage=false

            # entrypoints
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443

            # redirect http to https
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            
            # let's encrypt resolver
            - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
            - --certificatesresolvers.letsencrypt.acme.email=thedmdim@gmail.com
            - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
        ports:
            - 80:80
            - 443:443
        labels: 
            traefik.enable: "true"
        volumes:
            - ./letsencrypt:/letsencrypt:rw
            - /run/docker.sock:/var/run/docker.sock:ro
        networks:
            - app


