version: '3.8'

networks:
  app:
    driver: bridge

services:
  ytstalker:
    container_name: ytstalker
    image: ghcr.io/thedmdim/ytstalker
    restart: always
    volumes:
      - .:/usr/bin/ytstalker/db
    environment:
      DSN: db/${DSN}
      YT_API_KEY: ${YT_API_KEY}
    networks:
      - app

  caddy:
    container_name: caddy
    image: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy-config:/config
      - ./caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app