version: '3.8'

networks:
  ytstalker:
    driver: bridge

services:

  tele:
    container_name: tele
    image: ghcr.io/thedmdim/ytstalker/tele
    restart: always
    volumes:
      - .:/usr/bin/ytstalker/db
    environment:
      API_URL: app/api
      TG_TOKEN: ${TG_TOKEN}
    networks:
      - ytstalker

  app:
    container_name: app
    image: ghcr.io/thedmdim/ytstalker/app
    restart: always
    volumes:
      - .:/usr/bin/ytstalker/db
    environment:
      DSN: db/${DSN}
      YT_API_KEY: ${YT_API_KEY}
    networks:
      - ytstalker

  caddy:
    container_name: caddy
    image: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy-config:/config
      - ./caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - ytstalker