name: Deploy to Server

on:
  push:
    branches:
      - compose2

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build Image'
        run: |
          docker build -t ghcr.io/thedmdim/ytstalker:latest .
          docker push ghcr.io/thedmdim/ytstalker:latest
