name: Deploy to Server

on:
  push:
    branches:
      - compose

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
      - run: ko build ./app
