name: Deploy to Server

on:
  push:
    branches:
      - compose2

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
      - run: |
          echo "${GITHUB_TOKEN}" | ko login https://ghcr.io --username thedmdim --password-stdin
          ko build
